---
- hosts: localhost
  connection: local
  become: yes
#  become_method: sudo
#  become_user: ubuntu
  roles:
    - docker 
    - common
    - git
    - ansible-kubectl
    - git-project
    - dockertag
    - dockerbuild
#    - deployer
