- name: "Installing git-core"
  apt: state=installed name=git-core

- name: "Setting git global user.name 'th-deployment'"
  command: git config --global user.name th-deployment
  sudo: no

- name: "Setting git global user.email 'deployment@telenorhealth.com'"
  command: git config --global user.email deployment@telenorhealth.com
  sudo: no

- name: "Create /home/ubuntu/.ssh directory"
  file: state=directory path=/home/ubuntu/.ssh

- name: "Copy th-deployment private key file to /home/ubuntu/.ssh/"
  copy: src=id_rsa dest=/home/ubuntu/.ssh/id_rsa mode=0600 owner=ubuntu group=ubuntu

- name: "Copy git th-deployment public key file /home/ubuntu/.ssh/"
  copy: src=id_rsa.pub dest=/home/ubuntu/.ssh/id_rsa.pub mode=0644

- name: "Copy github config file to /home/ubuntu/.ssh/config"
  template: src=config dest=/home/ubuntu/.ssh/config mode=0654 owner=ubuntu group=ubuntu
  sudo: yes

- name: "Create /root/.ssh directory"
  file: state=directory path=/root/.ssh

- name: "Copy github config to /root/.ssh/config"
  template: src=config dest=/root/.ssh/config mode=0654 owner=root group=root
  sudo: yes
